version: '3.8'

services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    environment:
      - PYTHONUNBUFFERED=1
    command: []  # Default command, can be overridden with --force-refresh
    ports:
      - "8000:8000" 